services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecom-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=mongodb+srv://2312112_db_user:dbdinesh@e-commerce.azq6veg.mongodb.net/?retryWrites=true&w=majority&appName=E-commerce
      - PORT=5000
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecom-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules


